### ISSUE TITLE
mix deploy example as a starting point for my own application error with bin/build

### ISSUE THREAD

**Issue by jhaigh-xactly** [cogini/mix_deploy#11]
I ran into this issue when using mix deploy example as a starting point for my own application:

```
uilding digest files
Check your digested files at "priv/static"
===> Generating systemd files
* creating _build/prod/systemd/lib/systemd/system/profile-app.service
===> Generating deploy files
* creating bin/deploy-start
* creating bin/deploy-stop
* creating bin/deploy-restart
* creating bin/deploy-enable
* creating bin/deploy-create-users
* creating bin/deploy-create-dirs
* creating bin/deploy-set-perms
* creating bin/deploy-init-local
** (MatchError) no match of right hand side value: {:error, {:template, %ArgumentError{message: "cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[:deploy_dir, \"/etc/environment\"]\n"}}}
    lib/mix_deploy/templates.ex:20: MixDeploy.Templates.write_template/4
    lib/mix/tasks/deploy.ex:529: anonymous fn/4 in Mix.Tasks.Deploy.Generate.run/1
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/deploy.ex:529: Mix.Tasks.Deploy.Generate.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

Environment

Macosx

Steps

1. MIX_ENV=prod bin/build

**Comment by vimalearnest** [comment]
Fix : https://github.com/cogini/mix_deploy/pull/12
